image: node:20

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: dudaferreira/tw-todos-gha

before_script:
  - apk add --no-cache curl

build:
  stage: build
  script: 
    - echo "Building Docker image"
    - docker build -t $DOCKER_IMAGE .

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Logging in to Docker Hub.."
    - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
    - echo "Pushing Docker image.."
    - docker push $DOCKER_IMAGE
  only: 
    - master