name: ci
run-name: CI

on:
    pull_request:
        branches:
            - master

jobs: 
    run-test-and-build:
        uses: ./.github/workflows/test-and-build.yaml
        secrets: inherit

        