name: deploy
run-name: Deploy

on:
    - workflow_call

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: Check out 
              uses: actions/checkout@v4

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: dudaferreira/tw-todos-gha

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}


            
